[2024-10-08T08:36:21.966-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-08T08:36:21.989-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_predict.prediction manual__2024-10-08T11:35:58.788977+00:00 [queued]>
[2024-10-08T08:36:21.999-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_predict.prediction manual__2024-10-08T11:35:58.788977+00:00 [queued]>
[2024-10-08T08:36:22.000-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-08T08:36:22.014-0300] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): prediction> on 2024-10-08 11:35:58.788977+00:00
[2024-10-08T08:36:22.019-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=608) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T08:36:22.021-0300] {standard_task_runner.py:63} INFO - Started process 609 to run task
[2024-10-08T08:36:22.021-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_predict', 'prediction', 'manual__2024-10-08T11:35:58.788977+00:00', '--job-id', '119', '--raw', '--subdir', 'DAGS_FOLDER/Predict/preprocess_predict.py', '--cfg-path', '/tmp/tmpnig7n0ff']
[2024-10-08T08:36:22.022-0300] {standard_task_runner.py:91} INFO - Job 119: Subtask prediction
[2024-10-08T08:36:22.066-0300] {task_command.py:426} INFO - Running <TaskInstance: preprocess_predict.prediction manual__2024-10-08T11:35:58.788977+00:00 [running]> on host 4a07270c49a4
[2024-10-08T08:36:22.176-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_predict' AIRFLOW_CTX_TASK_ID='prediction' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T11:35:58.788977+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T11:35:58.788977+00:00'
[2024-10-08T08:36:22.177-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-08T08:36:22.179-0300] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venv92mru064 --python=python
[2024-10-08T08:36:22.181-0300] {process_utils.py:187} INFO - Output:
[2024-10-08T08:36:22.820-0300] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 216ms
[2024-10-08T08:36:22.821-0300] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venv92mru064, clear=False, no_vcs_ignore=False, global=False)
[2024-10-08T08:36:22.822-0300] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-08T08:36:22.823-0300] {process_utils.py:191} INFO -     added seed packages: pip==24.2
[2024-10-08T08:36:22.824-0300] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-08T08:36:22.858-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venv92mru064/bin/pip install -r /tmp/venv92mru064/requirements.txt
[2024-10-08T08:36:22.859-0300] {process_utils.py:187} INFO - Output:
[2024-10-08T08:36:24.316-0300] {process_utils.py:191} INFO - Collecting joblib (from -r /tmp/venv92mru064/requirements.txt (line 1))
[2024-10-08T08:36:24.318-0300] {process_utils.py:191} INFO -   Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
[2024-10-08T08:36:24.534-0300] {process_utils.py:191} INFO - Collecting numpy (from -r /tmp/venv92mru064/requirements.txt (line 2))
[2024-10-08T08:36:24.537-0300] {process_utils.py:191} INFO -   Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-08T08:36:24.750-0300] {process_utils.py:191} INFO - Collecting pandas (from -r /tmp/venv92mru064/requirements.txt (line 3))
[2024-10-08T08:36:24.751-0300] {process_utils.py:191} INFO -   Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
[2024-10-08T08:36:24.905-0300] {process_utils.py:191} INFO - Collecting scikit-learn (from -r /tmp/venv92mru064/requirements.txt (line 4))
[2024-10-08T08:36:24.906-0300] {process_utils.py:191} INFO -   Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
[2024-10-08T08:36:24.964-0300] {process_utils.py:191} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venv92mru064/requirements.txt (line 3))
[2024-10-08T08:36:24.965-0300] {process_utils.py:191} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-10-08T08:36:25.030-0300] {process_utils.py:191} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venv92mru064/requirements.txt (line 3))
[2024-10-08T08:36:25.032-0300] {process_utils.py:191} INFO -   Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
[2024-10-08T08:36:25.060-0300] {process_utils.py:191} INFO - Collecting tzdata>=2022.7 (from pandas->-r /tmp/venv92mru064/requirements.txt (line 3))
[2024-10-08T08:36:25.062-0300] {process_utils.py:191} INFO -   Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-10-08T08:36:25.205-0300] {process_utils.py:191} INFO - Collecting scipy>=1.6.0 (from scikit-learn->-r /tmp/venv92mru064/requirements.txt (line 4))
[2024-10-08T08:36:25.207-0300] {process_utils.py:191} INFO -   Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-08T08:36:25.259-0300] {process_utils.py:191} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn->-r /tmp/venv92mru064/requirements.txt (line 4))
[2024-10-08T08:36:25.260-0300] {process_utils.py:191} INFO -   Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2024-10-08T08:36:25.287-0300] {process_utils.py:191} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venv92mru064/requirements.txt (line 3))
[2024-10-08T08:36:25.288-0300] {process_utils.py:191} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-10-08T08:36:25.303-0300] {process_utils.py:191} INFO - Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
[2024-10-08T08:36:25.304-0300] {process_utils.py:191} INFO - Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
[2024-10-08T08:36:25.320-0300] {process_utils.py:191} INFO - Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
[2024-10-08T08:36:25.332-0300] {process_utils.py:191} INFO - Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
[2024-10-08T08:36:25.364-0300] {process_utils.py:191} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-10-08T08:36:25.366-0300] {process_utils.py:191} INFO - Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
[2024-10-08T08:36:25.368-0300] {process_utils.py:191} INFO - Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
[2024-10-08T08:36:25.403-0300] {process_utils.py:191} INFO - Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2024-10-08T08:36:25.405-0300] {process_utils.py:191} INFO - Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
[2024-10-08T08:36:25.406-0300] {process_utils.py:191} INFO - Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-10-08T08:36:25.597-0300] {process_utils.py:191} INFO - Installing collected packages: pytz, tzdata, threadpoolctl, six, numpy, joblib, scipy, python-dateutil, scikit-learn, pandas
[2024-10-08T08:36:40.772-0300] {process_utils.py:191} INFO - Successfully installed joblib-1.4.2 numpy-2.1.2 pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2024.2 scikit-learn-1.5.2 scipy-1.14.1 six-1.16.0 threadpoolctl-3.5.0 tzdata-2024.2
[2024-10-08T08:36:41.204-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venv92mru064/bin/python /tmp/venv-callmp8mjwbz/script.py /tmp/venv-callmp8mjwbz/script.in /tmp/venv-callmp8mjwbz/script.out /tmp/venv-callmp8mjwbz/string_args.txt /tmp/venv-callmp8mjwbz/termination.log
[2024-10-08T08:36:41.206-0300] {process_utils.py:187} INFO - Output:
[2024-10-08T08:36:42.964-0300] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-10-08T08:36:42.965-0300] {process_utils.py:191} INFO -   File "/tmp/venv-callmp8mjwbz/script.py", line 55, in <module>
[2024-10-08T08:36:42.966-0300] {process_utils.py:191} INFO -     res = task_prediction(*arg_dict["args"], **arg_dict["kwargs"])
[2024-10-08T08:36:42.966-0300] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:36:42.967-0300] {process_utils.py:191} INFO -   File "/tmp/venv-callmp8mjwbz/script.py", line 31, in task_prediction
[2024-10-08T08:36:42.968-0300] {process_utils.py:191} INFO -     prediction=regressor.predict(X_test)
[2024-10-08T08:36:42.969-0300] {process_utils.py:191} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:36:42.970-0300] {process_utils.py:191} INFO -   File "/tmp/venv92mru064/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 1063, in predict
[2024-10-08T08:36:42.971-0300] {process_utils.py:191} INFO -     X = self._validate_X_predict(X)
[2024-10-08T08:36:42.972-0300] {process_utils.py:191} INFO -         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:36:42.973-0300] {process_utils.py:191} INFO -   File "/tmp/venv92mru064/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 641, in _validate_X_predict
[2024-10-08T08:36:42.974-0300] {process_utils.py:191} INFO -     X = self._validate_data(
[2024-10-08T08:36:42.975-0300] {process_utils.py:191} INFO -         ^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:36:42.975-0300] {process_utils.py:191} INFO -   File "/tmp/venv92mru064/lib/python3.12/site-packages/sklearn/base.py", line 608, in _validate_data
[2024-10-08T08:36:42.977-0300] {process_utils.py:191} INFO -     self._check_feature_names(X, reset=reset)
[2024-10-08T08:36:42.978-0300] {process_utils.py:191} INFO -   File "/tmp/venv92mru064/lib/python3.12/site-packages/sklearn/base.py", line 535, in _check_feature_names
[2024-10-08T08:36:42.979-0300] {process_utils.py:191} INFO -     raise ValueError(message)
[2024-10-08T08:36:42.980-0300] {process_utils.py:191} INFO - ValueError: The feature names should match those that were passed during fit.
[2024-10-08T08:36:42.981-0300] {process_utils.py:191} INFO - Feature names seen at fit time, yet now missing:
[2024-10-08T08:36:42.982-0300] {process_utils.py:191} INFO - - color_beige
[2024-10-08T08:36:42.983-0300] {process_utils.py:191} INFO - - color_blue
[2024-10-08T08:36:42.983-0300] {process_utils.py:191} INFO - - color_brown
[2024-10-08T08:36:42.984-0300] {process_utils.py:191} INFO - - color_cherry
[2024-10-08T08:36:42.985-0300] {process_utils.py:191} INFO - - color_clove
[2024-10-08T08:36:42.986-0300] {process_utils.py:191} INFO - - ...
[2024-10-08T08:36:42.987-0300] {process_utils.py:191} INFO - 
[2024-10-08T08:36:43.501-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-08T08:36:43.516-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- color_beige
- color_blue
- color_brown
- color_cherry
- color_clove
- ...

[2024-10-08T08:36:43.523-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=preprocess_predict, task_id=prediction, run_id=manual__2024-10-08T11:35:58.788977+00:00, execution_date=20241008T113558, start_date=20241008T113621, end_date=20241008T113643
[2024-10-08T08:36:43.554-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 119 for task prediction (Process returned non-zero exit status 1.
The feature names should match those that were passed during fit.
Feature names seen at fit time, yet now missing:
- color_beige
- color_blue
- color_brown
- color_cherry
- color_clove
- ...
; 609)
[2024-10-08T08:36:43.575-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-08T08:36:43.595-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T08:36:43.598-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
