[2024-10-08T08:50:45.093-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-08T08:50:45.121-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_predict.prediction manual__2024-10-08T11:50:19.331490+00:00 [queued]>
[2024-10-08T08:50:45.134-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_predict.prediction manual__2024-10-08T11:50:19.331490+00:00 [queued]>
[2024-10-08T08:50:45.135-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-08T08:50:45.153-0300] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): prediction> on 2024-10-08 11:50:19.331490+00:00
[2024-10-08T08:50:45.162-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1308) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T08:50:45.164-0300] {standard_task_runner.py:63} INFO - Started process 1309 to run task
[2024-10-08T08:50:45.164-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_predict', 'prediction', 'manual__2024-10-08T11:50:19.331490+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/Predict/preprocess_predict.py', '--cfg-path', '/tmp/tmp_irdl5qq']
[2024-10-08T08:50:45.165-0300] {standard_task_runner.py:91} INFO - Job 129: Subtask prediction
[2024-10-08T08:50:45.215-0300] {task_command.py:426} INFO - Running <TaskInstance: preprocess_predict.prediction manual__2024-10-08T11:50:19.331490+00:00 [running]> on host 4a07270c49a4
[2024-10-08T08:50:45.328-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_predict' AIRFLOW_CTX_TASK_ID='prediction' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T11:50:19.331490+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T11:50:19.331490+00:00'
[2024-10-08T08:50:45.329-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-08T08:50:45.331-0300] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvvbguor96 --python=python
[2024-10-08T08:50:45.332-0300] {process_utils.py:187} INFO - Output:
[2024-10-08T08:50:45.986-0300] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 202ms
[2024-10-08T08:50:45.987-0300] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venvvbguor96, clear=False, no_vcs_ignore=False, global=False)
[2024-10-08T08:50:45.988-0300] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-08T08:50:45.989-0300] {process_utils.py:191} INFO -     added seed packages: pip==24.2
[2024-10-08T08:50:45.991-0300] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-08T08:50:46.024-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venvvbguor96/bin/pip install -r /tmp/venvvbguor96/requirements.txt
[2024-10-08T08:50:46.025-0300] {process_utils.py:187} INFO - Output:
[2024-10-08T08:50:47.699-0300] {process_utils.py:191} INFO - Collecting joblib (from -r /tmp/venvvbguor96/requirements.txt (line 1))
[2024-10-08T08:50:47.701-0300] {process_utils.py:191} INFO -   Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
[2024-10-08T08:50:47.966-0300] {process_utils.py:191} INFO - Collecting numpy (from -r /tmp/venvvbguor96/requirements.txt (line 2))
[2024-10-08T08:50:47.969-0300] {process_utils.py:191} INFO -   Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-08T08:50:48.261-0300] {process_utils.py:191} INFO - Collecting pandas (from -r /tmp/venvvbguor96/requirements.txt (line 3))
[2024-10-08T08:50:48.265-0300] {process_utils.py:191} INFO -   Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
[2024-10-08T08:50:48.478-0300] {process_utils.py:191} INFO - Collecting scikit-learn (from -r /tmp/venvvbguor96/requirements.txt (line 4))
[2024-10-08T08:50:48.480-0300] {process_utils.py:191} INFO -   Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
[2024-10-08T08:50:48.527-0300] {process_utils.py:191} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venvvbguor96/requirements.txt (line 3))
[2024-10-08T08:50:48.529-0300] {process_utils.py:191} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-10-08T08:50:48.612-0300] {process_utils.py:191} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venvvbguor96/requirements.txt (line 3))
[2024-10-08T08:50:48.615-0300] {process_utils.py:191} INFO -   Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
[2024-10-08T08:50:48.649-0300] {process_utils.py:191} INFO - Collecting tzdata>=2022.7 (from pandas->-r /tmp/venvvbguor96/requirements.txt (line 3))
[2024-10-08T08:50:48.651-0300] {process_utils.py:191} INFO -   Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-10-08T08:50:48.844-0300] {process_utils.py:191} INFO - Collecting scipy>=1.6.0 (from scikit-learn->-r /tmp/venvvbguor96/requirements.txt (line 4))
[2024-10-08T08:50:48.846-0300] {process_utils.py:191} INFO -   Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-08T08:50:48.897-0300] {process_utils.py:191} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn->-r /tmp/venvvbguor96/requirements.txt (line 4))
[2024-10-08T08:50:48.899-0300] {process_utils.py:191} INFO -   Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2024-10-08T08:50:48.933-0300] {process_utils.py:191} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venvvbguor96/requirements.txt (line 3))
[2024-10-08T08:50:48.935-0300] {process_utils.py:191} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-10-08T08:50:48.956-0300] {process_utils.py:191} INFO - Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
[2024-10-08T08:50:48.960-0300] {process_utils.py:191} INFO - Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
[2024-10-08T08:50:48.995-0300] {process_utils.py:191} INFO - Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
[2024-10-08T08:50:49.013-0300] {process_utils.py:191} INFO - Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
[2024-10-08T08:50:49.029-0300] {process_utils.py:191} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-10-08T08:50:49.031-0300] {process_utils.py:191} INFO - Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
[2024-10-08T08:50:49.034-0300] {process_utils.py:191} INFO - Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
[2024-10-08T08:50:49.073-0300] {process_utils.py:191} INFO - Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2024-10-08T08:50:49.075-0300] {process_utils.py:191} INFO - Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
[2024-10-08T08:50:49.078-0300] {process_utils.py:191} INFO - Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-10-08T08:50:49.329-0300] {process_utils.py:191} INFO - Installing collected packages: pytz, tzdata, threadpoolctl, six, numpy, joblib, scipy, python-dateutil, scikit-learn, pandas
[2024-10-08T08:51:04.896-0300] {process_utils.py:191} INFO - Successfully installed joblib-1.4.2 numpy-2.1.2 pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2024.2 scikit-learn-1.5.2 scipy-1.14.1 six-1.16.0 threadpoolctl-3.5.0 tzdata-2024.2
[2024-10-08T08:51:05.316-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venvvbguor96/bin/python /tmp/venv-calltznf5ztv/script.py /tmp/venv-calltznf5ztv/script.in /tmp/venv-calltznf5ztv/script.out /tmp/venv-calltznf5ztv/string_args.txt /tmp/venv-calltznf5ztv/termination.log
[2024-10-08T08:51:05.317-0300] {process_utils.py:187} INFO - Output:
[2024-10-08T08:51:07.085-0300] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-10-08T08:51:07.086-0300] {process_utils.py:191} INFO -   File "/tmp/venv-calltznf5ztv/script.py", line 55, in <module>
[2024-10-08T08:51:07.088-0300] {process_utils.py:191} INFO -     res = task_prediction(*arg_dict["args"], **arg_dict["kwargs"])
[2024-10-08T08:51:07.089-0300] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:51:07.090-0300] {process_utils.py:191} INFO -   File "/tmp/venv-calltznf5ztv/script.py", line 31, in task_prediction
[2024-10-08T08:51:07.091-0300] {process_utils.py:191} INFO -     prediction=regressor.predict(X_test)
[2024-10-08T08:51:07.092-0300] {process_utils.py:191} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:51:07.093-0300] {process_utils.py:191} INFO -   File "/tmp/venvvbguor96/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 1063, in predict
[2024-10-08T08:51:07.094-0300] {process_utils.py:191} INFO -     X = self._validate_X_predict(X)
[2024-10-08T08:51:07.095-0300] {process_utils.py:191} INFO -         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:51:07.096-0300] {process_utils.py:191} INFO -   File "/tmp/venvvbguor96/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 641, in _validate_X_predict
[2024-10-08T08:51:07.097-0300] {process_utils.py:191} INFO -     X = self._validate_data(
[2024-10-08T08:51:07.098-0300] {process_utils.py:191} INFO -         ^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:51:07.099-0300] {process_utils.py:191} INFO -   File "/tmp/venvvbguor96/lib/python3.12/site-packages/sklearn/base.py", line 608, in _validate_data
[2024-10-08T08:51:07.100-0300] {process_utils.py:191} INFO -     self._check_feature_names(X, reset=reset)
[2024-10-08T08:51:07.101-0300] {process_utils.py:191} INFO -   File "/tmp/venvvbguor96/lib/python3.12/site-packages/sklearn/base.py", line 535, in _check_feature_names
[2024-10-08T08:51:07.102-0300] {process_utils.py:191} INFO -     raise ValueError(message)
[2024-10-08T08:51:07.102-0300] {process_utils.py:191} INFO - ValueError: The feature names should match those that were passed during fit.
[2024-10-08T08:51:07.104-0300] {process_utils.py:191} INFO - Feature names unseen at fit time:
[2024-10-08T08:51:07.105-0300] {process_utils.py:191} INFO - - motor_type_petrol and gas
[2024-10-08T08:51:07.106-0300] {process_utils.py:191} INFO - 
[2024-10-08T08:51:07.569-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-08T08:51:07.579-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- motor_type_petrol and gas

[2024-10-08T08:51:07.585-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=preprocess_predict, task_id=prediction, run_id=manual__2024-10-08T11:50:19.331490+00:00, execution_date=20241008T115019, start_date=20241008T115045, end_date=20241008T115107
[2024-10-08T08:51:07.609-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 129 for task prediction (Process returned non-zero exit status 1.
The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- motor_type_petrol and gas
; 1309)
[2024-10-08T08:51:07.653-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-08T08:51:07.674-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T08:51:07.678-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
