[2024-10-08T08:49:28.722-0300] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-10-08T08:49:28.749-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: preprocess_predict.prediction manual__2024-10-08T11:49:04.029902+00:00 [queued]>
[2024-10-08T08:49:28.759-0300] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: preprocess_predict.prediction manual__2024-10-08T11:49:04.029902+00:00 [queued]>
[2024-10-08T08:49:28.760-0300] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-10-08T08:49:28.775-0300] {taskinstance.py:2330} INFO - Executing <Task(_PythonVirtualenvDecoratedOperator): prediction> on 2024-10-08 11:49:04.029902+00:00
[2024-10-08T08:49:28.781-0300] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=1187) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-10-08T08:49:28.782-0300] {standard_task_runner.py:63} INFO - Started process 1188 to run task
[2024-10-08T08:49:28.784-0300] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'preprocess_predict', 'prediction', 'manual__2024-10-08T11:49:04.029902+00:00', '--job-id', '127', '--raw', '--subdir', 'DAGS_FOLDER/Predict/preprocess_predict.py', '--cfg-path', '/tmp/tmpgfcsu1oe']
[2024-10-08T08:49:28.785-0300] {standard_task_runner.py:91} INFO - Job 127: Subtask prediction
[2024-10-08T08:49:28.838-0300] {task_command.py:426} INFO - Running <TaskInstance: preprocess_predict.prediction manual__2024-10-08T11:49:04.029902+00:00 [running]> on host 4a07270c49a4
[2024-10-08T08:49:28.945-0300] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='preprocess_predict' AIRFLOW_CTX_TASK_ID='prediction' AIRFLOW_CTX_EXECUTION_DATE='2024-10-08T11:49:04.029902+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-08T11:49:04.029902+00:00'
[2024-10-08T08:49:28.946-0300] {taskinstance.py:430} INFO - ::endgroup::
[2024-10-08T08:49:28.948-0300] {process_utils.py:183} INFO - Executing cmd: /home/***/.local/bin/python -m virtualenv /tmp/venvebh1ep21 --python=python
[2024-10-08T08:49:28.949-0300] {process_utils.py:187} INFO - Output:
[2024-10-08T08:49:29.720-0300] {process_utils.py:191} INFO - created virtual environment CPython3.12.3.final.0-64 in 211ms
[2024-10-08T08:49:29.721-0300] {process_utils.py:191} INFO -   creator CPython3Posix(dest=/tmp/venvebh1ep21, clear=False, no_vcs_ignore=False, global=False)
[2024-10-08T08:49:29.722-0300] {process_utils.py:191} INFO -   seeder FromAppData(download=False, pip=bundle, via=copy, app_data_dir=/home/***/.local/share/virtualenv)
[2024-10-08T08:49:29.724-0300] {process_utils.py:191} INFO -     added seed packages: pip==24.2
[2024-10-08T08:49:29.725-0300] {process_utils.py:191} INFO -   activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
[2024-10-08T08:49:29.759-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venvebh1ep21/bin/pip install -r /tmp/venvebh1ep21/requirements.txt
[2024-10-08T08:49:29.761-0300] {process_utils.py:187} INFO - Output:
[2024-10-08T08:49:31.389-0300] {process_utils.py:191} INFO - Collecting joblib (from -r /tmp/venvebh1ep21/requirements.txt (line 1))
[2024-10-08T08:49:31.392-0300] {process_utils.py:191} INFO -   Using cached joblib-1.4.2-py3-none-any.whl.metadata (5.4 kB)
[2024-10-08T08:49:31.646-0300] {process_utils.py:191} INFO - Collecting numpy (from -r /tmp/venvebh1ep21/requirements.txt (line 2))
[2024-10-08T08:49:31.648-0300] {process_utils.py:191} INFO -   Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-08T08:49:31.860-0300] {process_utils.py:191} INFO - Collecting pandas (from -r /tmp/venvebh1ep21/requirements.txt (line 3))
[2024-10-08T08:49:31.862-0300] {process_utils.py:191} INFO -   Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (89 kB)
[2024-10-08T08:49:32.031-0300] {process_utils.py:191} INFO - Collecting scikit-learn (from -r /tmp/venvebh1ep21/requirements.txt (line 4))
[2024-10-08T08:49:32.032-0300] {process_utils.py:191} INFO -   Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (13 kB)
[2024-10-08T08:49:32.089-0300] {process_utils.py:191} INFO - Collecting python-dateutil>=2.8.2 (from pandas->-r /tmp/venvebh1ep21/requirements.txt (line 3))
[2024-10-08T08:49:32.092-0300] {process_utils.py:191} INFO -   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl.metadata (8.4 kB)
[2024-10-08T08:49:32.170-0300] {process_utils.py:191} INFO - Collecting pytz>=2020.1 (from pandas->-r /tmp/venvebh1ep21/requirements.txt (line 3))
[2024-10-08T08:49:32.171-0300] {process_utils.py:191} INFO -   Using cached pytz-2024.2-py2.py3-none-any.whl.metadata (22 kB)
[2024-10-08T08:49:32.210-0300] {process_utils.py:191} INFO - Collecting tzdata>=2022.7 (from pandas->-r /tmp/venvebh1ep21/requirements.txt (line 3))
[2024-10-08T08:49:32.215-0300] {process_utils.py:191} INFO -   Using cached tzdata-2024.2-py2.py3-none-any.whl.metadata (1.4 kB)
[2024-10-08T08:49:32.402-0300] {process_utils.py:191} INFO - Collecting scipy>=1.6.0 (from scikit-learn->-r /tmp/venvebh1ep21/requirements.txt (line 4))
[2024-10-08T08:49:32.403-0300] {process_utils.py:191} INFO -   Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
[2024-10-08T08:49:32.459-0300] {process_utils.py:191} INFO - Collecting threadpoolctl>=3.1.0 (from scikit-learn->-r /tmp/venvebh1ep21/requirements.txt (line 4))
[2024-10-08T08:49:32.461-0300] {process_utils.py:191} INFO -   Using cached threadpoolctl-3.5.0-py3-none-any.whl.metadata (13 kB)
[2024-10-08T08:49:32.489-0300] {process_utils.py:191} INFO - Collecting six>=1.5 (from python-dateutil>=2.8.2->pandas->-r /tmp/venvebh1ep21/requirements.txt (line 3))
[2024-10-08T08:49:32.491-0300] {process_utils.py:191} INFO -   Using cached six-1.16.0-py2.py3-none-any.whl.metadata (1.8 kB)
[2024-10-08T08:49:32.506-0300] {process_utils.py:191} INFO - Using cached joblib-1.4.2-py3-none-any.whl (301 kB)
[2024-10-08T08:49:32.509-0300] {process_utils.py:191} INFO - Using cached numpy-2.1.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.0 MB)
[2024-10-08T08:49:32.532-0300] {process_utils.py:191} INFO - Using cached pandas-2.2.3-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
[2024-10-08T08:49:32.546-0300] {process_utils.py:191} INFO - Using cached scikit_learn-1.5.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.9 MB)
[2024-10-08T08:49:32.559-0300] {process_utils.py:191} INFO - Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
[2024-10-08T08:49:32.561-0300] {process_utils.py:191} INFO - Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
[2024-10-08T08:49:32.563-0300] {process_utils.py:191} INFO - Using cached scipy-1.14.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (40.8 MB)
[2024-10-08T08:49:32.606-0300] {process_utils.py:191} INFO - Using cached threadpoolctl-3.5.0-py3-none-any.whl (18 kB)
[2024-10-08T08:49:32.608-0300] {process_utils.py:191} INFO - Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
[2024-10-08T08:49:32.610-0300] {process_utils.py:191} INFO - Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
[2024-10-08T08:49:32.811-0300] {process_utils.py:191} INFO - Installing collected packages: pytz, tzdata, threadpoolctl, six, numpy, joblib, scipy, python-dateutil, scikit-learn, pandas
[2024-10-08T08:49:47.981-0300] {process_utils.py:191} INFO - Successfully installed joblib-1.4.2 numpy-2.1.2 pandas-2.2.3 python-dateutil-2.9.0.post0 pytz-2024.2 scikit-learn-1.5.2 scipy-1.14.1 six-1.16.0 threadpoolctl-3.5.0 tzdata-2024.2
[2024-10-08T08:49:48.450-0300] {process_utils.py:183} INFO - Executing cmd: /tmp/venvebh1ep21/bin/python /tmp/venv-call4b3w_9t3/script.py /tmp/venv-call4b3w_9t3/script.in /tmp/venv-call4b3w_9t3/script.out /tmp/venv-call4b3w_9t3/string_args.txt /tmp/venv-call4b3w_9t3/termination.log
[2024-10-08T08:49:48.452-0300] {process_utils.py:187} INFO - Output:
[2024-10-08T08:49:50.151-0300] {process_utils.py:191} INFO - Traceback (most recent call last):
[2024-10-08T08:49:50.152-0300] {process_utils.py:191} INFO -   File "/tmp/venv-call4b3w_9t3/script.py", line 55, in <module>
[2024-10-08T08:49:50.153-0300] {process_utils.py:191} INFO -     res = task_prediction(*arg_dict["args"], **arg_dict["kwargs"])
[2024-10-08T08:49:50.154-0300] {process_utils.py:191} INFO -           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:49:50.155-0300] {process_utils.py:191} INFO -   File "/tmp/venv-call4b3w_9t3/script.py", line 31, in task_prediction
[2024-10-08T08:49:50.156-0300] {process_utils.py:191} INFO -     prediction=regressor.predict(X_test)
[2024-10-08T08:49:50.158-0300] {process_utils.py:191} INFO -                ^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:49:50.159-0300] {process_utils.py:191} INFO -   File "/tmp/venvebh1ep21/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 1063, in predict
[2024-10-08T08:49:50.160-0300] {process_utils.py:191} INFO -     X = self._validate_X_predict(X)
[2024-10-08T08:49:50.161-0300] {process_utils.py:191} INFO -         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:49:50.162-0300] {process_utils.py:191} INFO -   File "/tmp/venvebh1ep21/lib/python3.12/site-packages/sklearn/ensemble/_forest.py", line 641, in _validate_X_predict
[2024-10-08T08:49:50.162-0300] {process_utils.py:191} INFO -     X = self._validate_data(
[2024-10-08T08:49:50.163-0300] {process_utils.py:191} INFO -         ^^^^^^^^^^^^^^^^^^^^
[2024-10-08T08:49:50.164-0300] {process_utils.py:191} INFO -   File "/tmp/venvebh1ep21/lib/python3.12/site-packages/sklearn/base.py", line 608, in _validate_data
[2024-10-08T08:49:50.166-0300] {process_utils.py:191} INFO -     self._check_feature_names(X, reset=reset)
[2024-10-08T08:49:50.167-0300] {process_utils.py:191} INFO -   File "/tmp/venvebh1ep21/lib/python3.12/site-packages/sklearn/base.py", line 535, in _check_feature_names
[2024-10-08T08:49:50.167-0300] {process_utils.py:191} INFO -     raise ValueError(message)
[2024-10-08T08:49:50.168-0300] {process_utils.py:191} INFO - ValueError: The feature names should match those that were passed during fit.
[2024-10-08T08:49:50.169-0300] {process_utils.py:191} INFO - Feature names unseen at fit time:
[2024-10-08T08:49:50.170-0300] {process_utils.py:191} INFO - - motor_type_petrol and gas
[2024-10-08T08:49:50.171-0300] {process_utils.py:191} INFO - Feature names seen at fit time, yet now missing:
[2024-10-08T08:49:50.172-0300] {process_utils.py:191} INFO - - type_minivan / minibus
[2024-10-08T08:49:50.173-0300] {process_utils.py:191} INFO - 
[2024-10-08T08:49:50.612-0300] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-10-08T08:49:50.626-0300] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 437, in execute
    return super().execute(context=serializable_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 759, in execute_callable
    result = self._execute_python_callable_in_subprocess(python_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 514, in _execute_python_callable_in_subprocess
    raise AirflowException(error_msg) from None
airflow.exceptions.AirflowException: Process returned non-zero exit status 1.
The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- motor_type_petrol and gas
Feature names seen at fit time, yet now missing:
- type_minivan / minibus

[2024-10-08T08:49:50.643-0300] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=preprocess_predict, task_id=prediction, run_id=manual__2024-10-08T11:49:04.029902+00:00, execution_date=20241008T114904, start_date=20241008T114928, end_date=20241008T114950
[2024-10-08T08:49:50.660-0300] {standard_task_runner.py:110} ERROR - Failed to execute job 127 for task prediction (Process returned non-zero exit status 1.
The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- motor_type_petrol and gas
Feature names seen at fit time, yet now missing:
- type_minivan / minibus
; 1188)
[2024-10-08T08:49:50.670-0300] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-10-08T08:49:50.688-0300] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-08T08:49:50.691-0300] {local_task_job_runner.py:222} INFO - ::endgroup::
